#Deployment part
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatdeployment
  namespace: dev
  labels:
    app: tomcatcontainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcatcontainer
  template:
    metadata:
      labels:
        app: tomcatcontainer
    spec:
      containers:
      - name: tomcatcontainer
        image: corentdocker/jenkinsmaasrndtomcat:latest
        ports:
        - containerPort: 8080
---
#Service  part
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcatcontainer
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer    #Cluster IP  NodePort
---
