#Deployment part
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat.deployment
  labels:
    app: tomcatcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatcontainer
  template:
    metadata:
      labels:
        app: tomcatcontainer
    spec:
      containers:
      - name: tomcatcontainer
        image: corentdocker/jenkinsapp
        ports:
        - containerPort: 8080
---
#Service  part
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcatcontainer
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer    #Cluster IP  NodePort
---